name: 📖 Documentation improvement
description: Create a report to help us improve the dlordinal documentation.
title: "[DOC] "
labels: ["documentation"]

body:
- type: textarea
  attributes:
    label: Describe the issue linked to the documentation
    description: >
      Tell us what part of the documentation you think needs improvement.
  validations:
    required: true
- type: textarea
  attributes:
    label: Suggest a potential alternative/fix
    description: >
      Tell us how you think the documentation could be improved.
