name: "Run Tests"

on:
  push:
    branches:
      - main
    paths:
      - "tutorials/**"
      - "dlordinal/**"
      - ".github/workflows/**"
  pull_request:
    branches:
      - main
    paths:
      - "tutorials/**"
      - "dlordinal/**"
      - ".github/workflows/**"

jobs:
  tests-codecov:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install codecov
        pip install pytest-cov
        pip install .

    - name: Run tests for codecov
      run: |
        pytest --cov=dlordinal --cov-report=xml
      timeout-minutes: 20

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
